module.exports = {
  jobLocations: [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Nashik",
    "Aurangabad",
    "Delhi",
    "New Delhi",
    "Gurugram",
    "Noida",
    "Faridabad",
    "Bengaluru",
    "Mysuru",
    "Mangalore",
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Hyderabad",
    "Visakhapatnam",
    "Vijayawada",
    "Kolkata",
    "Howrah",
    "Chandigarh",
    "Mohali",
    "Jaipur",
    "Udaipur",
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Lucknow",
    "Kanpur",
    "Indore",
    "Bhopal",
    "Patna",
    "Ranchi",
    "Bhubaneswar",
    "Cuttack",
    "Kochi",
    "Thiruvananthapuram",
    "Trichy",
    "Goa",
  ],
  jobCategories: [
    "Information Technology",
    "Software Development",
    "Web & Mobile App Development",
    "Data Science & Analytics",
    "Cybersecurity",
    "Cloud Computing & DevOps",
    "AI & Machine Learning",
    "BPO / KPO / Customer Support",
    "Sales & Business Development",
    "Digital Marketing & SEO",
    "Content Writing & Editing",
    "Graphic Design & UI/UX",
    "Finance & Accounting",
    "Banking & Insurance",
    "Chartered Accountancy",
    "Human Resources & Recruitment",
    "Engineering (Mechanical, Civil, Electrical)",
    "Architecture & Interior Design",
    "Construction & Real Estate",
    "Education & Teaching",
    "Healthcare & Nursing",
    "Pharmaceuticals & Biotech",
    "Hospitality & Tourism",
    "Retail & E-commerce",
    "Manufacturing & Production",
    "Logistics & Supply Chain",
    "Transport & Delivery",
    "Legal & Compliance",
    "Media & Entertainment",
    "Film & Video Production",
    "Sports & Fitness",
    "Government & Public Sector",
    "NGOs & Social Work",
  ],
  jobTypes: [
    "Full-time",
    "Part-time",
    "Internship",
    "Freelance / Contract",
    "Temporary",
    "Remote",
    "Hybrid",
  ],
  applicationStatus: [
    "applied",
    "withdrawn",
    "in review",
    "shortlisted",
    "rejected",
    "hired",
  ],
};
